admin:
  build: ./app
  volumes:
    - "./app:/src/app"
  ports:
    - "3030:3000"
  links:
    - "redis"
    - "mongodb"
  command: nodemon -L app/bin/www

wx:
  build: ./app
  volumes:
    - "./app:/src/app"
  ports:
    - "3031:3000"
  links:
    - "redis"
    - "mongodb"
  command: nodemon -L app/bin/www

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "8080:8080"
    - "8081:8081"
  volumes:
    - /www/public
  volumes_from:
    - admin
    - wx
  links:
    - admin
    - wx

redis:
  image: redis:latest
  command: redis-server --appendonly yes
  volumes:
    - ./data:/data

mongodb:
  image: mongo:latest
  container_name: "mongodb"
  environment:
    - MONGO_DATA_DIR=/data/db
    - MONGO_LOG_DIR=/dev/null
  volumes:
    - ./data/db:/data/db
  ports:
    - 27018:27017
  command: mongod --smallfiles --logpath=/dev/null # --quiet
