web:
  build: .
  volumes:
    - "./app:/src/app"
  ports:
    - "3030:3000"
  links:
    - "db:redis"

db:
  image: redis:latest
  command: redis-server --appendonly yes
  volumes:
  - ./data:/data

